---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: nodeapp

spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodeapp
  # Pod template
  template:
    metadata:
      labels:
         app: nodeapp
    spec:
      containers:
      - name: nodeapp
        image: opusidea/nodeappdemo:1.0.0
        imagePullPolicy: IfNotPresent
        env:
        - name: REDIS_HOST
          value: redis # correspond au nom donné (metadata.name) donné au svc/redis