---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: nodeapp

spec:
  replicas: 4
  selector:
    matchLabels:
      app: nodeapp
  # Pod template
  template:
    metadata:
      labels:
         app: nodeapp
    spec:
      containers:
      - name: nodeapp
        image: opusidea/nodeappdemo:1.0.1
        imagePullPolicy: IfNotPresent
        env:
        - name: REDIS_HOST
          value: redis # correspond au nom donné (metadata.name) donné au svc/redis
---
kind: Service
apiVersion: v1
metadata:
  name: nodeapp # utilisé en résolution DNS
spec:
  type: NodePort # connectivité externe/interne
  selector:
    app: nodeapp
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 31230
...