---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: deploy-apache

spec:
  replicas: 2
  selector:
    matchLabels:
      app: apache
  # Pod template
  template:
    metadata:
      labels:
         app: apache
    spec:
      containers:
      - name: apache
        image: httpd:2.4-alpine