# jenkins/agent + python
# image à utiliser en tant que docker agent template
# d'un noeud temporaire (cloud) dans Jenkins
FROM jenkins/agent:alpine-jdk11
USER root
RUN apk add python3
RUN apk add py3-pip
USER jenkins