---
- name: Exemple 9
  hosts: slave1

  vars:
    title: Formation Ansible
    apache_dir: /varrrrrrrrr/www/html

  tasks:
  - name: Stats for {{ apache_dir }}
    stat:
      path: "{{ apache_dir }}"
    register: out

  #- debug: var=out

  - name: Update ownership on {{ apache_dir }}
    file:
      path: "{{ apache_dir }}"
      owner: "{{ ansible_user }}"
    become: yes
    #when: out.stat.exists

  - name: process and copy template file
    template:
      src: templates/facts.html.j2
      dest: "{{ apache_dir }}/facts.html"
    when: out.stat.exists

...