---
- name: Exemple 12
  hosts: slave1
  gather_facts: no

  # import des variables définies dans les fichiers externes
  vars_files:
  - ./vars/demo.yaml

  vars_prompt:
  - name: username
    prompt: "Nom du compte utilisateur"
    private: no # yes par défaut, cache la saisie

  tasks:
  - debug: var=packages
  - debug: var=username
...